mattermost/mattermost-plugin-mscalendar

- server/remote/msgraph/call.go
#Summary
This PR fixes an issue where full paths, that already contained the baseURL, were getting prepended with the baseURL.  Now, relative paths are determined by looking at the path string and checking that the first character is a `/`.
Also fixed an issue where inBody was not getting set to the buf value, thus alway `nil`.
> Only prepend baseURL to relative paths

- server/api/api.go
- server/api/calendar.go
- server/plugin/command/command.go
- server/plugin/command/create_calendar.go
- server/plugin/command/create_event.go
- server/plugin/command/delete_calendar.go
- server/plugin/command/find_meeting_times.go
- server/plugin/command/get_calendars.go
- server/plugin/command/help.go
- server/plugin/http/oauth2_connect.go
- server/remote/client.go
- server/remote/event.go
- server/remote/msgraph/create_calendar.go
- server/remote/msgraph/create_event.go
- server/remote/msgraph/delete_calendar.go
- server/remote/msgraph/find_meeting_times.go
- server/remote/msgraph/get_user_calendars.go
**Draft PR**
The main objective of this PR is to implement the `createEvent()` method.
Additionally, the PR adds the following:
* new subtypes to the `Event` Struct
* `CreateCalendar()` method and slash command
* `DeleteCalendar()` method and slash command
* more help text for available slash commands
**Additional Notes About the Draft PR**
While debugging the `CreateEvent()` method, I have been hardcoding the values into the `Event` struct, rather than implementing the slash command parsing.  Please assume additional commits to have similar hard-coded types until debugging is finished.
> Implement Create Calendar Event Method

- server/remote/msgraph/get_schedule_batched.go
This PR takes into account when a Graph API error occurs with an individual call inside of the batch call for `getSchedule`. If there is an error with any of them, the operation bails and no user statuses get updated. The way the caller is set up, it should be fairly trivial to change the code to simply "skip over" the ones that had errors if we wish to do it that way.
https://mattermost.atlassian.net/browse/MM-21691
> [MM-21691] Handle errors for getSchedule call

- server/command/command.go
There is a typo in the autocomplete description for the `/mscalendar` command, and since the command is case-sensitive it will not work if typed as shown. It should be `findmeetings`. I didn't find any other instances of this typo in the repository.
> Fix findmeetings typo

- server/command/daily_summary.go
- server/mscalendar/availability.go
- server/mscalendar/availability_test.go
- server/mscalendar/client.go
- server/mscalendar/daily_summary.go
- server/mscalendar/daily_summary_test.go
- server/mscalendar/filters.go
- server/mscalendar/mock_mscalendar/mock_mscalendar.go
- server/mscalendar/oauth2.go
- server/mscalendar/oauth2_test.go
- server/mscalendar/user.go
- server/store/daily_summary_store.go
- server/store/mock_store/mock_store.go
- server/store/user_store.go
- server/utils/kvstore/hashed_key.go
- server/utils/kvstore/kvstore.go
- server/utils/kvstore/plugin_store.go
This PR uses the `Atomic` KVOption to ensure that the kv value used for the operation is up to date upon save.
The atomic saves are used in all contexts where the current value affects the operation being done. For other cases, we are creating new entries in the store, in which case the names of the methods are StoreNewUser etc.
Fixes https://github.com/mattermost/mattermost-plugin-mscalendar/issues/47
> Use KVSetWithOptions with Atomic: true

- server/store/oauth2_store.go
The `oauth2_store` was saving its values with the key prefix `sub_` when it should be using `oauth2_`
Fixes #77
> Use correct prefix for OAuth2 store keys

- server/command/subscribe.go
- server/jobs/job_manager.go
- server/jobs/renew_job.go
- server/mscalendar/subscription.go
- server/plugin/plugin.go
- server/remote/msgraph/subscription.go
- Added a simple job to renew all user subscriptions every 24 hours
- Increased the default subscription expiry to 48 hours
Fixes https://github.com/mattermost/mattermost-plugin-mscalendar/issues/54
> Added a job to renew user subscriptions

- server/mscalendar/settings.go
- server/utils/settingspanel/settings.go
Remove the server error that occurred when a new user opened the settings panel, and there was no previous panel to delete. This was caused by not handling the "not found" error of the store.
#104
> [GH104] Check when the error when cleaning a setting post is not found

- plugin.json
A made a PR for this a while ago but missed the `plugin.json` file.
Fixes #114
> Remove references to "common"

- server/mscalendar/notification.go
- server/mscalendar/notification_test.go
- server/mscalendar/views/calendar.go
The event invitation details logic was not using the user's timezone when displaying the event times
Fixes https://github.com/mattermost/mattermost-plugin-mscalendar/issues/128
> Use timezone when displaying event details

- server/mscalendar/availability.go
- server/mscalendar/settings.go
- server/mscalendar/welcome_flow.go
- server/store/flow_store.go
- server/store/setting_store.go
- server/store/user_store.go
Allow status change to support DND and Away. Settings added to both settings and login flow.
Fix #89
> [GH-89] Allow status change to support DND and Away

- server/mscalendar/daily_summary.go
- server/store/setting_store.go
There seems to be a panic in master that happens when the daily summary settings are set to nil. This should never happen, but maybe a weird status in the system is triggering this.
This PR makes sure the daily summary setting is set by adding a default in every point it is present.
Another solution could be remove the indirection and trust the go defaults.
None
> Fix panic when Daily Summary is nil for a user

- build/custom.mk
Add back build info for `/mscalendar info`. This was broken in https://github.com/mattermost/mattermost-plugin-mscalendar/pull/196.
Fixes https://github.com/mattermost/mattermost-plugin-mscalendar/issues/231
> Add back build info

- server/remote/msgraph/call.go
For context, please see https://community.mattermost.com/core/pl/a7m4w3tbufgzdj1trqkt3mj3tw
Here is the error we're currently getting when trying to create a superuser token for the status sync feature:
> Error during user status sync job. err=not able to filter the super user client: msgraph GetSuperuserToken: status: 400 Bad Request: json: cannot unmarshal string into Go struct field ErrorResponse.error of type msgraph.ErrorObject
We're receiving a `400 Bad Request` from Microsoft's API, with a response body that does not match the expected `ErrorObject` struct. Since the `Unmarshal` fails, we don't have any other context for what actual error occurred.
This PR makes it so we log the response body in the case that this unmarshal fails.
---
This error is originally happening here on line …
> On failure to unmarshal msgraph API error, log whole response body

- providers/gcal.go
- providers/mscalendar.go
- server/command/daily_summary.go
- server/command/info.go
- server/mscalendar/calendar.go
- server/mscalendar/settings_daily_summary.go
- server/mscalendar/user.go
- server/mscalendar/welcome_flow.go
- server/mscalendar/welcomer.go
- server/plugin/plugin.go
- server/utils/oauth2connect/oauth2.go
- server/utils/oauth2connect/oauth2_complete.go
Refactor to use the `config.ProviderConfig` data to display text in the plugin, mainly the display name and the command trigger in help text around the commands and events.
> [GCAL] Refactor Microsoft Calendar references to provider references

- server/plugin/plugin.go
- server/remote/gcal/remote.go
- server/remote/mock_remote/mock_remote.go
- server/remote/msgraph/remote.go
- server/remote/remote.go
Refactored the logic that checks for the correct configuration to the remotes instead of doing it in the main plugin load, since each remote has different requirements now.
> [GCAL] Move configuration readyness logic to remotes

- server/mscalendar/availability.go
- server/remote/gcal/remote.go
- In order to retrieve the timezone we need `CalendarScope`. We will need it later to retrieve calendars anyway.
- For `deliverReminders` to work properly, since we do not have a superuser credential around (and we now use the `FilterCopy` logic) we had to change it's internal logic as well.
> [GCAL] Fix event notifications not working due to missing scope permissions plus internal state

- Makefile
- build/setup.mk
Add the correct `MANIFEST_FILE` environment variable to all `bin/manifest` calls that didn't have it setup.
> [GCAL] Use correct `MANIFEST_FILE` on `bin/manifest` calls.

- providers/gcal.go
- providers/mscalendar.go
- server/command/command.go
- server/config/config.go
- server/mscalendar/settings.go
- server/mscalendar/welcome_flow.go
- server/plugin/plugin.go
Only enable event notifications if the provider allows it, along with any relevant settings and wizard option
The subscribe/unsubscribe commands are removed from autocompletion and only admin can use them from now on.
https://mattermost.atlassian.net/browse/MM-53918
> [GCAL] Event notifications behind a feature flag

- server/command/command.go
- server/command/daily_summary.go
- server/mscalendar/daily_summary_test.go
- server/mscalendar/views/calendar.go
- Fixes command trigger not being shown with the `/trigger summary` command help.
- Adds autocomplete data to the `/trigger summary` command.
- Removes the "Join meeting" column from table vies.
- Escape subject symbols: `|`, `[`, `]`,`>`
- https://mattermost.atlassian.net/browse/MM-53887
- https://mattermost.atlassian.net/browse/MM-53889
- https://mattermost.atlassian.net/browse/MM-53892
- https://mattermost.atlassian.net/browse/MM-53893
> [GCAL] Summary command fixes

- server/mscalendar/oauth2.go
- server/mscalendar/oauth2_test.go
Fixes a small typo I found where the username and the command trigger were in wrong positions.
> typo: user already connected message

- server/mscalendar/calendar.go
- server/mscalendar/daily_summary.go
- server/mscalendar/daily_summary_test.go
In order to be consistent with reminders, exclude events that have been rejected from the agenda commands.
https://mattermost.atlassian.net/browse/MM-54172
> [GCAL/MSCAL] Exclude rejected events from agenda commands

- server/mscalendar/settings_daily_summary.go
- server/utils/settingspanel/bool_setting.go
- server/utils/settingspanel/option_setting.go
- Uses the `primary` style in setting buttons for the enabled setting
- Removes the `Current value` line for bool and daily summary settings.
https://mattermost.atlassian.net/browse/MM-53891
> [GCAL/MSCAL] Make selected setting use primary button style to show it as active and remove "Current value" line

- server/command/command.go
- server/command/disconnect_test.go
Adds a link to connect the account directly in the message shown to users when they tried to use a command that requires a connected account.
https://mattermost.atlassian.net/browse/MM-53883
> [GCAL/MSCAL] Show link to connect on error message "user is not connected"

- server/mscalendar/oauth2.go
- server/mscalendar/welcome_flow.go
- server/store/user_store.go
- Reduce welcome steps by removing "confirm status change" (default: no) and "Status during meetings" (default: away).
https://mattermost.atlassian.net/browse/MM-53886
> [GCAL/MSCAL] Reduce welcome steps 

- Makefile
Changed the build command for the webapp to `build` so it can be deployed in production enviornments.
> [GCAL/MSCAL] Use `npm run bulid` when making plugin bundles

- calendar/engine/availability.go
Moved the code that adds users to process at the end of the process loop, since if any error is found the user will be added anyway but we won't have the information to process it.
> fix: only add user to process availability if no errors are found

- README.md
- docs/admin-guide.md
This PR organizes the README section as per the instructions in the issue description. I have used the reviews given for a similar issue, namely the Bitbucket README and have tried to incorporate the instructions given by the reviewers. Hence, I haven't relinked the images as per given in the ticket. If this step is necessary, do let me know and I'll make the required changes. These are the main changes that have been done:
1. Created a table of contents as mentioned
2. Made a new admin-guide file under the docs folder 
3. Moved all configuration details into the admin-guide file
4. Linked all the links and the table of contents according to the changes made
Fixes https://github.com/mattermost/mattermost/issues/25168
> #25168 Microsoft Calendar O365 README > Split out admin content to child pages

- plugin.json
Replaced legacy/broken GitBook link with permalink [via Marketing](https://docs.google.com/spreadsheets/d/1O601H_A0IM8pR3FOfue29_C8flGV7xK3ts-tJUVDHHg/edit#gid=0).
Addresses: https://mattermost.atlassian.net/browse/MM-55436
> Replaced legacy GitBook URLs with PL link

- calendar/engine/daily_summary.go
This pull request fixes a crash that was caused when processing the daily summary for an user that couldn't be retrieved. Since we use the output from the `LoadUser` call in the `Warnf` call, plugin was crashing.
> fix: avoid using output from failing function

- calendar/plugin/plugin.go
- Fixed the issue of the plugin crashing on an empty site URL
- This will also fix the Google Calendar plugin crashing as seen in https://github.com/mattermost/mattermost-plugin-google-calendar/issues/72 after updating it with the new package
> [MM-595] Fix issue of plugin crashing on empty site url

- calendar/api/api.go
- Replace hard-coded HTTP verb strings with constants from `net/http`
N/A
> Replace hard coded HTTP verb strings with net/http constants

- calendar/command/command.go
- calendar/engine/oauth2.go
- calendar/engine/views/calendar.go
- calendar/remote/notification.go
- msgraph/get_super_user_token.go
- Fix typo `GetNotificationData()` in comment
- Fix typo "there's" in comment
- Fix typo "deactivated" in string
- Rename variable `command` to `cmd` to not collide with imported package
- Remove unnecessary variable `params` 
NA
> Fix typo, remove unnecessary params variable

- calendar/engine/oauth2.go
- calendar/engine/oauth2_test.go
- According to the [issue linked below](https://github.com/mattermost/mattermost-plugin-mscalendar/issues/367), the users are not able to accept the permissions in the modal. That modal [was not present](https://github.com/mattermost/mattermost-plugin-mscalendar/issues/367#issuecomment-2135402695) in the previous plugin release and the users were able to connect just by clicking the link from MM.
- The modal is occurring because of a [code change](https://github.com/mattermost/mattermost-plugin-mscalendar/blob/b4f752d6669a9958e7b7b16c757d2d1e5dc7f8a6/calendar/engine/oauth2.go#L51) in [this PR](https://github.com/mattermost/mattermost-plugin-mscalendar/pull/267/files). The [prompt param](https://pkg.go.dev/golang.org/x/oauth2@v0.15.0#section-readme) in the URL is forcing the users to …
> [GH-367] Remove "prompt" param from auth code URL

- msgraph/get_default_calendar_view.go
- Add path escaping to remote ID in getCalendarViewURL
Fixes #395 
Fixes https://mattermost.atlassian.net/browse/MM-60182
> [GH-395] Add path escaping to remote ID in getCalendarViewURL

- msgraph/remote.go
- Add timeout to http client
- Http client has a [default timeout](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/httpclient/httpclient-timeout-method#remarks) of 100 sec. We updated it to ~5~ 60 sec.
Fixes #394 
Fixes https://mattermost.atlassian.net/browse/MM-60185
> [GH-394] Add timeout to http client

- calendar/api/api.go
- calendar/telemetry/logger.go
- msgraph/get_schedule_batched.go
- Escape string in URL generation
- Fix doc comment
- Replace hard coded HTTP status code with constant
NA
> Escape string, fix comment, use constant

- plugin.json
Bumps plugin version to v1.3.4 to force internal plugin version, GH tag, and filename version are in sync.
NONE
> Bump version to 1.3.4

- Makefile
Fixing failing CI by updating golangci-lint version from 1.51.1 to 1.55.0
Refer to this [conversation](https://github.com/github/codeql-action/issues/2581) for more reference
> Fix failing CI by updating golang-ci lint version

- calendar/engine/daily_summary.go
- calendar/engine/daily_summary_test.go
- calendar/engine/notification_format.go
- calendar/engine/views/calendar.go
- Fix issue of `01:25AM` not being treated as valid time entry for hours
-  Replaced chars with HTML entities in reminder posts for location, description and other fields
Fixes https://github.com/mattermost/mattermost-plugin-mscalendar/issues/457
Fixes https://github.com/mattermost/mattermost-plugin-mscalendar/issues/455
> Fix bugs reported by QA on v1.4.0-rc2
