- README.md
Very early POC for the README with plugin configuration details.
> Initial Add for README

- server/mscalendar/settings_daily_summary.go
On Daily Summary Setting, change the logic to always show 12 instead of 0.
Fix #127
> [GH-127]  Replace the `0` with `12` to indicate noon and midnight 

- server/command/help.go
Removed:
- info (mainly a debug command)
- showcals
- createcal
- deletecal
- createevent
- findmeetings
Added:
- disconnect
- settings
- summary
Fixes https://github.com/mattermost/mattermost-plugin-mscalendar/issues/45
> Fix help text

- plugin-gcal.json
Fixes some Microsoft references in the google calendar manifest.
> [GCAL] Manifest typos

- server/mscalendar/daily_summary.go
Add some more information to some log lines to address what's happening in the test server
> [GCAL] Better logging information

- server/manifest.go
- server/mscalendar/daily_summary_test.go
- server/mscalendar/views/calendar.go
Remove join event column (broken from merges)
> [GCAL] Remove join event column (broken from merges)

- server/remote/gcal/event.go
Send notifications to attendees when creating an event
https://mattermost.atlassian.net/browse/MM-54156
> [GCAL] Send notifications to attendees when creating an event

- server/api/events.go
- webapp/src/components/modals/create_event_form.tsx
- webapp/src/components/time_selector.tsx
- webapp/src/utils/datetime.ts
- Backend validation for start time or end time in the past
- Frontend control of time fields if the selected date is today
https://mattermost.atlassian.net/browse/MM-54131
> [GCAL/MSCAL] Control start/date times if the selected date is today

- server/utils/flow/handler.go
- server/utils/settingspanel/handler.go
Workaround for the [database replication problem](https://community.mattermost.com/core/pl/nphtmkowcjd8ic76tbqtapx6nc) present in the welcome flow and the settings panel.
https://mattermost.atlassian.net/browse/MM-54032
> [GCAL/MSCAL] Workaround for database replication issue present in welcome flow and settings panel

- .gitignore
- README.md
- calendar/config/config.go
- calendar/engine/daily_summary.go
- calendar/engine/mscalendar.go
- calendar/telemetry/tracker.go
- calendar/utils/pluginapi/api.go
- Add `.idea` to .gitignore
- Fix misc typos
- Remove redundant parens
- Remove extra "the" in comment
- Minor formatting so line of code isn't so long
N/A
> Add .idea to .gitignore and fix typos

- msgraph/get_super_user_token.go
-  Add path escaping to "OAuth2Authority"
Fixes https://mattermost.atlassian.net/browse/MM-60003
> [MM-60003] Add path escaping to "OAuth2Authority"

- calendar/api/autocomplete.go
- calendar/api/connected_user.go
- calendar/api/events.go
- calendar/api/notification.go
- calendar/plugin/plugin.go
- Adding error logging
Fixes https://mattermost.atlassian.net/browse/MM-60021
> [MM-60021] Adding error logging

- calendar/utils/bot/poster.go
- docs/admin-guide.md
- Fix doc comments
- Apply IDE recommendations in admin guide
N/A
> Fix doc comments, apply IDE suggestions in admin guide

- calendar/jobs/job_manager.go
- calendar/plugin/plugin.go
- Fix typo in "removes"
- Add path escape to URL generation
NA
> Fix typo, add path escape to url generation

- go.mod
- go.sum
- msgraph/handle_webhook.go
-  Added logic to sanitize the validation token for webhook requests
- Updated doc link for notification validation
Fixes https://mattermost.atlassian.net/browse/MM-60204
> [MM-60204] Added logic to sanitize the validation token for webhook requests

- README.md
- plugin.json
Bump plugin version to v1.3.2
NONE
> Bump plugin version to v1.3.2

- Makefile
Fixes: https://github.com/mattermost/delivery-platform/actions/runs/10633556632/job/29478893029
Related: https://hub.mattermost.com/private-core/pl/966uk6jqa3frdjwqwd6bcfr8dw
> fix: Comply with unified release process

- calendar/engine/calendar_test.go
- calendar/engine/test_utils.go
Added server testcases for engine/calendar.go file
>  Added server testcases for engine/calendar.go file

- calendar/api/autocomplete_test.go
- calendar/api/test_utils.go
Added server testcases for api/autocomplete.go
> [MM-860]: Added server testcases for api/autocomplete.go

- calendar/engine/calendar_test.go
- calendar/engine/daily_summary_test.go
- calendar/engine/test_utils.go
Summary
Added server testcase for engine/daily_summary.go file
> Add engine/daily summary.go tescase

- Makefile
Fixed several mismatched `endif` statements.  Same as google-calandar PR fixing the same.
NONE
> Fix missing endif and remove extra endif

- calendar/engine/notification_format.go
Fix rendering of updated event post
> Fix rendering of updated event post
